#!/bin/bash

# 检查输入参数
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <repo_name> <commit_hash> [--headless] [--email <email>] [--change-number <number>]"
    exit 1
fi

# 定义常量
MAX_FUNCTION_LINES=4000

REPO_NAME=$1
COMMIT_HASH=$2
HEADLESS=false
EMAIL=""
CHANGE_NUMBER=""

# 解析命令行参数
shift 2 # 跳过前两个位置参数
while [[ $# -gt 0 ]]; do
    case $1 in
    --headless)
        HEADLESS=true
        shift
        ;;
    --email)
        EMAIL="$2"
        shift 2
        ;;
    --change-number)
        CHANGE_NUMBER="$2"
        shift 2
        ;;
    *)
        echo "Unknown parameter: $1"
        exit 1
        ;;
    esac
done

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
OUTPUT_DIR="$SCRIPT_DIR/output"
ERROR_LOG="$OUTPUT_DIR/error.log"
log() {
    local message="$1"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")

    # 统一使用tee输出到stdout和日志文件
    echo "[$timestamp] [RUN-REVIEW-SH] $message" | tee -a "$ERROR_LOG"
    printf "" >&1 # 强制刷新
}

COMMIT_FUNCTIONS="${REPO_NAME}-${COMMIT_HASH}.commit.functions"
COMMENT_HTML="${REPO_NAME}-${COMMIT_HASH}.comment.html"
COMMENT_JSON="${REPO_NAME}-${COMMIT_HASH}.comment.json"

# 获取当前脚本的目录
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

COMMIT_FUNCTIONS_FILE="$SCRIPT_DIR/output/$COMMIT_FUNCTIONS"
COMMENT_HTML_FILE="$SCRIPT_DIR/output/$COMMENT_HTML"
COMMENT_JSON_FILE="$SCRIPT_DIR/output/$COMMENT_JSON"
REPO_DIR="$SCRIPT_DIR/repos/$REPO_NAME"

TS_SCRIPT_DIR="$SCRIPT_DIR/auto_review_ui/scripts"

CWDS() {
    pushd "$TS_SCRIPT_DIR" >/dev/null || exit 1
}

CWDE() {
    popd >/dev/null || exit 1
}

# 调用code_diff.py
python3 "$SCRIPT_DIR/code_diff/code_diff.py" --repo "$REPO_DIR" --commit "$COMMIT_HASH" --output "$COMMIT_FUNCTIONS_FILE" 2>&1
if [ $? -ne 0 ]; then
    log "SCRIPT_FAILURE: commit functions generation failed"
    exit 1
fi

if [ ! -s "$SCRIPT_DIR/output/$COMMIT_FUNCTIONS" ] || [ $(wc -l <"$SCRIPT_DIR/output/$COMMIT_FUNCTIONS" 2>/dev/null || echo 0) -gt $MAX_FUNCTION_LINES ]; then
    log "no commit functions found in code diff or too many lines (>$MAX_FUNCTION_LINES)"
    exit 2
fi

# 调用auto_review.ts
log "Starting auto_review.ts script..."

# 设置环境变量强制输出不缓冲
export NODE_ENV=production
export CI=true
export FORCE_COLOR=0

# 创建临时文件来捕获错误输出
TEMP_ERROR_FILE=$(mktemp)

# 构建参数数组
REVIEW_ARGS=(
    "--repo-name" "$REPO_NAME"
    "--commit-functions" "$COMMIT_FUNCTIONS_FILE"
    "--output" "$COMMENT_HTML_FILE"
)

if [ "$HEADLESS" == true ]; then
    REVIEW_ARGS+=("--headless")
fi

if [ -n "$EMAIL" ]; then
    REVIEW_ARGS+=("--email" "$EMAIL")
fi

log "Command: timeout 1200 yarn tsx \"$TS_SCRIPT_DIR/auto_review.ts\" ${REVIEW_ARGS[*]}"
# 使用临时文件捕获stderr，同时保持stdout的实时输出
CWDS
timeout 1200 yarn tsx "$TS_SCRIPT_DIR/auto_review.ts" "${REVIEW_ARGS[@]}" \
    2>"$TEMP_ERROR_FILE" | tee >(while IFS= read -r line; do
        log "$line"
    done)
review_tsx_exit_code=${PIPESTATUS[0]}
CWDE

# 如果有错误输出，将其记录到日志
if [ -s "$TEMP_ERROR_FILE" ]; then
    log "Error output from auto_review.ts:"
    cat "$TEMP_ERROR_FILE" | while IFS= read -r line; do
        log "STDERR: $line"
    done
fi

# 清理临时文件
rm -f "$TEMP_ERROR_FILE"
log "auto_review.ts finished with exit code: $review_tsx_exit_code"

if [ $review_tsx_exit_code -ne 0 ]; then
    log "SCRIPT_FAILURE: LLM review failed"
    exit 1
fi

if [ ! -s "$COMMENT_HTML_FILE" ]; then
    log "SCRIPT_FAILURE: no comments generated by LLM"
    exit 1
fi

# 调用parse_review.py
if [ -n "$CHANGE_NUMBER" ]; then
    python3 "$SCRIPT_DIR/parse_review.py" "$COMMENT_HTML_FILE" --output "$COMMENT_JSON_FILE" --push-to-gerrit --change-num "$CHANGE_NUMBER"
else
    python3 "$SCRIPT_DIR/parse_review.py" "$COMMENT_HTML_FILE" --output "$COMMENT_JSON_FILE"
fi
if [ $? -ne 0 ]; then
    log "SCRIPT_FAILURE: comment JSON generation failed"
    exit 1
fi

exit 0
